"""MonitoringAgent -- Step 8 ("Monitoring") of the ZERO X-RAY ->
Government Future Engine evolution.

Makes a stored Prevent trigger (Step 5, read-only, unmodified) actually
mean something: given a `prevention_id`, this agent re-checks each of
its triggers against the LATEST already-stored Predict/Challenge
result for that service and reports whether the trigger's threshold is
currently breached.

======================================================================
WHAT "MONITORING" MEANS HERE, PRECISELY
======================================================================
This is an ON-DEMAND, deterministic RE-CHECK against already-computed,
already-stored data -- not a background scheduler, not a cron job, and
not a new Predict/Challenge run. "Live" means the check reflects
whatever the most recent stored Predict/Challenge result for this
service actually says right now, not that anything runs continuously
in the background. Every number this agent reports is copied directly
from a real stored row (`predictions.result_json` /
`challenges.result_json`) -- never recomputed, never estimated, never
generated by an LLM. There is no LLM call anywhere in this file.

======================================================================
DETERMINISM
======================================================================
For a given (trigger, latest stored Predict result, latest stored
Challenge result), `check_trigger` always returns the same
`current_value`/`breached`/`evidence` -- a plain threshold comparison
over data that was already fixed when it was stored. Repeated calls
against unchanged stored data return identical results.

======================================================================
HONESTY ABOUT WHAT'S UNKNOWN
======================================================================
If no Predict/Challenge result has ever been stored for this service,
or the specific vulnerability a CHALLENGE_RECURRENCE_TRIGGER is
watching for didn't recur in the latest stored Challenge, this agent
reports `current_value: None`, `breached: False`, and says so in
`evidence` -- it never invents a number to fill the gap.
"""

from datetime import datetime, timezone
from core.result_provenance import build_provenance
from core.backend_language import normalize_lang, text as backend_text


def _now_iso():
    return datetime.now(timezone.utc).isoformat()


class MonitoringAgent:

    def __init__(self, lang="en"):
        self.lang = normalize_lang(lang)

    def check_trigger(self, trigger, service_id, tenant_id, prediction_store, challenge_store):
        watch_metric = trigger.get("watch_metric")

        if watch_metric == "prediction_confidence":
            return self._check_prediction_confidence(trigger, service_id, tenant_id, prediction_store)

        if watch_metric == "challenge_severity":
            return self._check_challenge_severity(trigger, service_id, tenant_id, challenge_store)

        return {
            "current_value": None,
            "breached": False,
            "checked_against": None,
            "evidence": backend_text("monitor_unknown", self.lang, metric=watch_metric),
        }

    def _check_prediction_confidence(self, trigger, service_id, tenant_id, prediction_store):
        stored = prediction_store.list_predictions_for_service(service_id, tenant_id)
        if not stored:
            return {
                "current_value": None,
                "breached": False,
                "checked_against": None,
                "evidence": backend_text("monitor_no_predict", self.lang),
            }
        latest = stored[0]  # list_predictions_for_service orders DESC by created_at
        items = (latest.get("result") or {}).get("predictions") or []
        if not items:
            return {
                "current_value": None,
                "breached": False,
                "checked_against": latest.get("id"),
                "evidence": backend_text("monitor_predict_empty", self.lang, id=latest.get("id")),
            }
        current_value = round(max(item.get("confidence", 0.0) for item in items), 2)
        threshold = trigger.get("threshold_value", 0.0)
        breached = current_value >= threshold
        return {
            "current_value": current_value,
            "breached": breached,
            "checked_against": latest.get("id"),
            "evidence": backend_text("monitor_predict_value", self.lang, id=latest.get("id"), value=current_value, threshold=threshold),
        }

    def _check_challenge_severity(self, trigger, service_id, tenant_id, challenge_store):
        stored = challenge_store.list_challenges_for_service(service_id, tenant_id)
        if not stored:
            return {
                "current_value": None,
                "breached": False,
                "checked_against": None,
                "evidence": backend_text("monitor_no_challenge", self.lang),
            }
        latest = stored[0]  # list_challenges_for_service orders DESC by created_at
        vulnerabilities = (latest.get("result") or {}).get("vulnerabilities") or []
        target_id = trigger.get("source_vulnerability_id")
        match = next((v for v in vulnerabilities if v.get("vulnerability_id") == target_id), None)
        if match is None:
            return {
                "current_value": None,
                "breached": False,
                "checked_against": latest.get("id"),
                "evidence": backend_text("monitor_challenge_missing", self.lang, target=target_id, id=latest.get("id")),
            }
        current_value = match.get("severity")
        threshold = trigger.get("threshold_value", 0.0)
        breached = current_value is not None and current_value >= threshold
        return {
            "current_value": current_value,
            "breached": breached,
            "checked_against": latest.get("id"),
            "evidence": backend_text("monitor_challenge_value", self.lang, id=latest.get("id"), value=current_value, target=target_id, threshold=threshold),
        }

    def run(self, stored_prevention_result, service_id, tenant_id, prediction_store, challenge_store):
        triggers = stored_prevention_result.get("triggers", [])
        checks = []
        for trigger in triggers:
            result = self.check_trigger(trigger, service_id, tenant_id, prediction_store, challenge_store)
            checks.append({
                "trigger_id": trigger.get("trigger_id"),
                "watch_metric": trigger.get("watch_metric"),
                "threshold_value": trigger.get("threshold_value"),
                **result,
            })
        generated_at = _now_iso()
        refs = [item.get("checked_against") for item in checks if item.get("checked_against")]
        return {
            "generated_at": generated_at,
            "provenance": build_provenance("DETERMINISTIC", evidence_references=refs, generated_at=generated_at),
            "checks": checks,
        }
