import { useEffect, useState } from "react";
import { useLanguage } from "../i18n/useLanguage";
import { translateApiError } from "../i18n/apiErrors";
import { useAuth } from "../auth/AuthContext";
import {
  predictService,
  createScenario,
  createChallenge,
  createEvolution,
  createPrevention,
  runMonitoringCheck,
  listAlerts,
  getMonitoringSchedule,
  updateMonitoringSchedule,
} from "../api";

// ZERO X-RAY Intelligence panel -- Steps 1-5 of the Government Future
// Engine evolution (Predict -> Simulate -> Challenge -> Evolve ->
// Prevent), wired to the real, already-tested backend endpoints only.
// No mock data, no invented fields: every value rendered below is
// read directly from a real API response.
//
// i18n note: the panel's own labels/hints/buttons follow the same
// local COPY[lang] pattern already used by Dashboard.jsx/ServiceForm.jsx.
// Detailed findings are rendered verbatim from the backend. The frontend
// does not translate or rephrase them; backend agents receive the selected
// language and fall back to English when localized text is unavailable.

const COPY = {
  en: {
    kicker: "GOVERNMENT FUTURE ENGINE",
    title: "ZERO X-RAY Intelligence",
    intro:
      "Run each stage in order using the real ID produced by the previous one. Nothing below is simulated in the frontend — every result comes from a live backend call.",
    englishNote:
      "Detailed findings are generated by the backend in the selected language when available; English is used as the fallback.",
    noServiceId:
      "No service_id was returned for this analysis, so ZERO X-RAY Intelligence can't run yet. Re-run the analysis to get one.",

    statusIdle: "NOT RUN",
    statusRunning: "RUNNING",
    statusDone: "DONE",
    statusError: "ERROR",
    retryHint: "The request failed — you can try again.",

    predictTitle: "1 · Predict",
    predictHint: "Predicts possible future risks and demand.",
    runPredict: "Run Predict",
    rerunPredict: "Re-run Predict",
    dataSufficiency: "data_sufficiency",
    analysesLabel: "analyses",
    journeysLabel: "journeys",
    predictionIdLabel: "prediction_id",
    noPredictions:
      "No recurring pattern was found yet — this is expected until the service has been analyzed more than once. Simulate/Challenge can still be run in Manual mode below.",
    confidenceLabel: "confidence",

    simulateTitle: "2 · Simulate",
    simulateHint: "Runs what-if scenarios.",
    runSimulate: "Run Simulate",
    rerunSimulate: "Re-run Simulate",
    autoScenario: "Automatic (recommended)",
    autoScenarioHint:
      "Automatically generates and runs every scenario relevant to this service (step failure, integration failure, SLA delay, demand spike, and payment/approval/missing-data when applicable) — no manual input or Predict result required.",
    autoScenariosHeading: "Generated scenarios",
    noAutoScenarios: "No scenarios could be generated automatically for this service.",
    autoCategories: {
      STEP_FAILURE: "Step failure",
      INTEGRATION_FAILURE: "Integration / API failure",
      SLA_DELAY: "SLA delay",
      DEMAND_SPIKE: "Demand spike",
      PAYMENT_FAILURE: "Payment failure",
      APPROVAL_DELAY: "Approval delay",
      MISSING_DATA: "Missing data",
    },
    fromPrediction: "From Predict result",
    runPredictFirst: "(run Predict first)",
    manualScenario: "Manual scenario",
    scenarioTypeLabel: "Scenario type",
    selectStep: "Select a step…",
    selectIntegration: "Select an integration…",
    noStepsAvailable: "No steps available from this analysis.",
    noIntegrationsAvailable: "No integrations available from this analysis.",
    scenarioIdLabel: "scenario_id",
    citizenImpact: "Citizen impact",
    governmentImpact: "Government impact",
    overallRisk: "Overall risk score",
    citizenOutcomeAffected: "Citizen outcome affected",
    citizenOutcomeYes: "Yes",
    citizenOutcomeNo: "No",
    insightWhatHappened: "What happened",
    insightWhyItMatters: "Why it matters",
    insightImpact: "Impact",
    insightRecommendation: "Recommendation",
    insightBeforeAfter: "Before → After",
    likelihoodLabel: "likelihood",
    affectedSteps: "Affected steps",

    challengeTitle: "3 · Challenge",
    challengeHint: "Stress-tests the future service design.",
    runChallenge: "Run Challenge",
    rerunChallenge: "Re-run Challenge",
    linkPrediction: "Link Predict result",
    noneYet: "(none yet)",
    strategiesHint: "Leave all unchecked to run every strategy (default).",
    challengeIdLabel: "challenge_id",
    casesExecuted: "case(s) executed",
    noVulnerabilities: "No vulnerability crossed a detection threshold.",
    severityLabel: "severity",
    targetLabel: "target",

    evolveTitle: "4 · Evolve",
    evolveHint: "Improves the design using detected weaknesses.",
    runEvolve: "Run Evolve",
    rerunEvolve: "Re-run Evolve",
    needChallengeFirst: "Run Challenge first to get a challenge_id.",
    evolutionIdLabel: "evolution_id",
    basedOnChallenge: "based on challenge",
    noProposals: "No structural fix applied to any discovered vulnerability.",
    fixesLabel: "fixes",
    protectedLabel: "PROTECTED",
    currentLabel: "Current",
    proposedLabel: "Proposed",
    exposureBefore: "exposure before",
    exposureAfter: "exposure after (estimate)",
    notCalculable: "not calculable from stored data",
    skippedLabel: "Skipped",

    preventTitle: "5 · Prevent",
    preventHint: "Creates preventive actions before problems reach citizens.",
    runPrevent: "Run Prevent",
    rerunPrevent: "Re-run Prevent",
    needEvolveFirst: "Run Evolve first to get an evolution_id.",
    preventionIdLabel: "prevention_id",
    basedOnEvolution: "based on evolution",
    noTriggers: "No trigger could be defined from this evolution's proposals.",
    watchingLabel: "watching",
    thresholdLabel: "threshold",
    actionLabel: "Action if triggered",
    protectedStep: "PROTECTED STEP",

    stepperPredict: "Predict",
    stepperSimulate: "Simulate",
    stepperChallenge: "Challenge",
    stepperEvolve: "Evolve",
    stepperPrevent: "Prevent",

    monitoringTitle: "Monitoring & Alerts",
    monitoringHint:
      "Checks prevention conditions over time.",
    runMonitoring: "Run monitoring check",
    rerunMonitoring: "Re-run monitoring check",
    needPreventFirst: "Run Prevent first to get a prevention_id.",
    monitoringNote:
      "Monitoring re-checks the prevention triggers against the latest stored Predict/Challenge results.",
    scheduledMonitoring: "Scheduled monitoring",
    scheduledMonitoringHint: "Optional background checks reuse the same monitoring rules and stored alert behavior.",
    enabledLabel: "Enabled",
    frequencyLabel: "Frequency",
    hourlyLabel: "Hourly",
    dailyLabel: "Daily",
    saveSchedule: "Save schedule",
    scheduleSaved: "Monitoring schedule saved.",
    notificationsDatabaseOnly: "Notifications: database only",
    checkedAgainst: "checked against",
    noDataYet: "no stored data yet",
    breachedYes: "BREACHED",
    breachedNo: "within threshold",
    alertCreated: "alert created",
    alertAlreadyOpen: "alert already open",
    alertResolved: "alert resolved",
    alertNone: "no alert",
    alertsListTitle: "Stored alerts for this service",
    noAlertsYet: "No alerts have been recorded for this service yet.",
    refreshAlerts: "Refresh alerts",
    alertStatusTriggered: "TRIGGERED",
    alertStatusResolved: "RESOLVED",
    currentAlertsHeading: "Current monitoring run",
    historicalAlertsHeading: "Previous runs (historical)",
    historicalAlertBadge: "previous run",

    simpleProblem: "Problem",
    simpleConsequence: "What happens if it fails?",
    simpleRisk: "Risk Level",
    simpleRecommendation: "What does ZERO X-RAY recommend?",
    technicalDetails: "Technical Details",
    riskLow: "Low",
    riskMedium: "Medium",
    riskHigh: "High",
    predictionPatternProblem: "A recurring pattern has been detected in this service.",
    predictionPatternConsequence: "If the pattern continues, it may keep affecting service performance or customer experience.",
    predictionRecommendation: "Review the repeated evidence and address the recurring cause before it becomes persistent.",
    simulationFailureProblem: "This scenario shows what could go wrong in the service.",
    simulationNoOutcomeImpact: "The issue affects internal work, but the current result does not show that the customer would lose the final service outcome.",
    simulationOutcomeImpact: "The customer may be unable to complete the service, or may receive the result late.",
    challengeRecommendations: {
      SINGLE_POINT_OF_FAILURE: "Reduce downstream dependency on this step so one failure does not stop the service.",
      CASCADING_FAILURE_PATH: "Contain the failure so it cannot propagate through later service steps.",
      SLA_FRAGILITY: "Add an explicit service-time safeguard and early warning before delays spread.",
      DEMAND_FRAGILITY: "Add capacity or an alternate path so demand spikes do not interrupt delivery.",
      CRITICAL_PATH_EXPOSURE: "Reduce the critical dependency on this step and add a resilient alternate path where possible.",
      CUSTOMER_FACING_EXPOSURE: "Protect the customer-facing outcome with a fallback or recovery path.",
    },
    evolveProblem: "The current service design has a weakness that can cause a failure or delay.",
    evolveConsequence: "If nothing changes, the same issue may happen again and affect service delivery.",
    preventProblem: "This risk needs an early warning before it becomes a service problem.",
    preventConsequence: "If the warning level is reached, the team should act before customers are affected.",
    preventRecommendation: "Take the proposed preventive action as soon as this risk reaches the warning level.",
    monitoringProblem: "A service risk has reached a level that needs attention.",
    monitoringBreached: "This risk is now above the accepted warning level and needs action.",
    monitoringSafe: "This risk is still within the accepted warning level.",
    monitoringRecommendation: "Start with the highest-risk issue and apply its linked preventive action.",
    currentValueLabel: "Current value",
    monitoringSummaryTitle: "Monitoring summary",
    monitoringSummaryProblem: (count) => `${count} service risk${count === 1 ? "" : "s"} currently need attention.`,
    monitoringSummaryConsequence: (high, medium, low) => `${high} high, ${medium} medium, and ${low} low priority.`,
    monitoringSummaryRecommendation: "Handle the highest-risk issue first, then review the remaining risks in order of priority.",
    showAllMonitoring: "View all monitoring details",
    showCurrentAlerts: "View current alert details",
    showHistoricalAlerts: (count) => `Previous alert history (${count})`,
    affectedSummary: (affected, total) => `${affected} of ${total} service steps could be affected.`,
    foundAcrossTargets: (count) => `This same issue was found in ${count} service step${count === 1 ? "" : "s"}.`,
    highestRiskLabel: "Highest risk",
    groupedDetails: (count) => `View affected steps (${count})`,
    preventionAcrossTargets: (count) => `${count} warning point${count === 1 ? "" : "s"} are linked to this same risk.`,
  },

  ar: {
    kicker: "محرك مستقبل الخدمات الحكومية",
    title: "ذكاء ZERO X-RAY",
    intro:
      "شغّل كل مرحلة بالترتيب باستخدام المعرّف الحقيقي الناتج عن المرحلة السابقة. لا شيء أدناه يُحاكى في الواجهة الأمامية — كل نتيجة تأتي من استدعاء فعلي للخادم.",
    englishNote:
      "يولّد الخادم التفاصيل التحليلية باللغة المحددة عند توفرها، وتُستخدم الإنجليزية كلغة احتياطية عند عدم توفر نص عربي.",
    noServiceId:
      "لم يُرجَع service_id لهذا التحليل، لذلك لا يمكن تشغيل ذكاء ZERO X-RAY بعد. أعد تشغيل التحليل للحصول عليه.",

    statusIdle: "لم يُشغَّل",
    statusRunning: "قيد التشغيل",
    statusDone: "منجَز",
    statusError: "خطأ",
    retryHint: "فشل الطلب — يمكنك المحاولة مرة أخرى.",

    predictTitle: "١ · التنبؤ",
    predictHint: "يتوقع المخاطر المستقبلية المحتملة والطلب.",
    runPredict: "تشغيل التنبؤ",
    rerunPredict: "إعادة تشغيل التنبؤ",
    dataSufficiency: "كفاية البيانات",
    analysesLabel: "تحليلات",
    journeysLabel: "رحلات",
    predictionIdLabel: "معرّف التنبؤ",
    noPredictions:
      "لم يُعثر على نمط متكرر بعد — وهذا متوقّع إلى أن يُحلَّل النطاق أكثر من مرة. يمكن تشغيل المحاكاة/الاختبار في الوضع اليدوي أدناه رغم ذلك.",
    confidenceLabel: "درجة الثقة",

    simulateTitle: "٢ · المحاكاة",
    simulateHint: "يشغّل سيناريوهات ماذا لو.",
    runSimulate: "تشغيل المحاكاة",
    rerunSimulate: "إعادة تشغيل المحاكاة",
    autoScenario: "تلقائي (موصى به)",
    autoScenarioHint:
      "يولّد ويشغّل تلقائيًا كل سيناريو ذي صلة بهذه الخدمة (فشل خطوة، فشل تكامل، تأخير في مستوى الخدمة، ارتفاع الطلب، وفشل الدفع/تأخير الموافقة/نقص البيانات عند انطباقها) — دون الحاجة لإدخال يدوي أو نتيجة تنبؤ.",
    autoScenariosHeading: "السيناريوهات المولَّدة",
    noAutoScenarios: "تعذّر توليد أي سيناريو تلقائيًا لهذه الخدمة.",
    autoCategories: {
      STEP_FAILURE: "فشل خطوة",
      INTEGRATION_FAILURE: "فشل تكامل / واجهة برمجية",
      SLA_DELAY: "تأخير في مستوى الخدمة",
      DEMAND_SPIKE: "ارتفاع الطلب",
      PAYMENT_FAILURE: "فشل الدفع",
      APPROVAL_DELAY: "تأخير الموافقة",
      MISSING_DATA: "نقص البيانات",
    },
    fromPrediction: "من نتيجة التنبؤ",
    runPredictFirst: "(شغّل التنبؤ أولًا)",
    manualScenario: "سيناريو يدوي",
    scenarioTypeLabel: "نوع السيناريو",
    selectStep: "اختر خطوة…",
    selectIntegration: "اختر تكاملًا…",
    noStepsAvailable: "لا توجد خطوات متاحة من هذا التحليل.",
    noIntegrationsAvailable: "لا توجد تكاملات متاحة من هذا التحليل.",
    scenarioIdLabel: "معرّف السيناريو",
    citizenImpact: "الأثر على المتعامل",
    governmentImpact: "الأثر على الجهة الحكومية",
    overallRisk: "درجة المخاطرة الكلية",
    citizenOutcomeAffected: "تأثر نتيجة الخدمة للمتعامل",
    citizenOutcomeYes: "نعم",
    citizenOutcomeNo: "لا",
    insightWhatHappened: "ما الذي حدث",
    insightWhyItMatters: "لماذا يهم",
    insightImpact: "الأثر",
    insightRecommendation: "التوصية",
    insightBeforeAfter: "قبل ← بعد",
    likelihoodLabel: "الاحتمالية",
    affectedSteps: "الخطوات المتأثرة",

    challengeTitle: "٣ · التحدي",
    challengeHint: "يختبر تصميم الخدمة المستقبلية تحت الضغط.",
    runChallenge: "تشغيل التحدي",
    rerunChallenge: "إعادة تشغيل التحدي",
    linkPrediction: "ربط نتيجة التنبؤ",
    noneYet: "(لا يوجد بعد)",
    strategiesHint: "اترك الكل بلا تحديد لتشغيل كل الاستراتيجيات (الافتراضي).",
    challengeIdLabel: "معرّف التحدي",
    casesExecuted: "حالة تم تنفيذها",
    noVulnerabilities: "لم تتجاوز أي ثغرة عتبة الاكتشاف.",
    severityLabel: "الخطورة",
    targetLabel: "الهدف",

    evolveTitle: "٤ · التطوير",
    evolveHint: "يحسّن التصميم باستخدام نقاط الضعف المكتشفة.",
    runEvolve: "تشغيل التطوير",
    rerunEvolve: "إعادة تشغيل التطوير",
    needChallengeFirst: "شغّل التحدي أولًا للحصول على معرّف التحدي.",
    evolutionIdLabel: "معرّف التطوير",
    basedOnChallenge: "استنادًا إلى التحدي",
    noProposals: "لم يُطبَّق أي إصلاح هيكلي على أي ثغرة مكتشَفة.",
    fixesLabel: "يعالج",
    protectedLabel: "محمية",
    currentLabel: "الحالي",
    proposedLabel: "المقترح",
    exposureBefore: "التعرّض قبل",
    exposureAfter: "التعرّض بعد (تقدير)",
    notCalculable: "غير قابل للحساب من البيانات المخزَّنة",
    skippedLabel: "تم تجاوزها",

    preventTitle: "٥ · الوقاية",
    preventHint: "ينشئ إجراءات وقائية قبل أن تصل المشكلات إلى المواطنين.",
    runPrevent: "تشغيل الوقاية",
    rerunPrevent: "إعادة تشغيل الوقاية",
    needEvolveFirst: "شغّل التطوير أولًا للحصول على معرّف التطوير.",
    preventionIdLabel: "معرّف الوقاية",
    basedOnEvolution: "استنادًا إلى التطوير",
    noTriggers: "تعذّر تحديد أي مشغّل من مقترحات هذا التطوير.",
    watchingLabel: "المراقَب",
    thresholdLabel: "العتبة",
    actionLabel: "الإجراء عند التفعيل",
    protectedStep: "خطوة محمية",

    stepperPredict: "التنبؤ",
    stepperSimulate: "المحاكاة",
    stepperChallenge: "التحدي",
    stepperEvolve: "التطوير",
    stepperPrevent: "الوقاية",

    monitoringTitle: "المراقبة والتنبيهات",
    monitoringHint:
      "يتحقق من شروط الوقاية بمرور الوقت.",
    runMonitoring: "تشغيل فحص المراقبة",
    rerunMonitoring: "إعادة تشغيل فحص المراقبة",
    needPreventFirst: "شغّل الوقاية أولًا للحصول على معرّف الوقاية.",
    monitoringNote:
      "يفحص هذا أحدث نتائج التنبؤ/التحدي المخزَّنة فقط. لا يُرسل بريدًا إلكترونيًا أو رسالة نصية أو أي تنبيه خارجي — كل تنبيه أدناه هو سجل مخزَّن يمكنك مراجعته.",
    checkedAgainst: "تم الفحص مقابل",
    noDataYet: "لا توجد بيانات مخزَّنة بعد",
    breachedYes: "تجاوز العتبة",
    breachedNo: "ضمن الحد المسموح",
    alertCreated: "تم إنشاء تنبيه",
    alertAlreadyOpen: "تنبيه مفتوح بالفعل",
    alertResolved: "تم حل التنبيه",
    alertNone: "لا يوجد تنبيه",
    scheduledMonitoring: "المراقبة المجدولة",
    scheduledMonitoringHint: "فحوصات خلفية اختيارية تستخدم نفس قواعد المراقبة وسجلات التنبيه الحالية.",
    enabledLabel: "مفعّلة",
    frequencyLabel: "التكرار",
    hourlyLabel: "كل ساعة",
    dailyLabel: "يوميًا",
    saveSchedule: "حفظ الجدول",
    scheduleSaved: "تم حفظ جدول المراقبة.",
    notificationsDatabaseOnly: "الإشعارات: قاعدة البيانات فقط",
    alertsListTitle: "التنبيهات المخزَّنة لهذه الخدمة",
    noAlertsYet: "لم يُسجَّل أي تنبيه لهذه الخدمة بعد.",
    refreshAlerts: "تحديث التنبيهات",
    alertStatusTriggered: "مُفعَّل",
    alertStatusResolved: "محلول",
    currentAlertsHeading: "دورة المراقبة الحالية",
    historicalAlertsHeading: "الدورات السابقة (سجل تاريخي)",
    historicalAlertBadge: "دورة سابقة",

    simpleProblem: "المشكلة",
    simpleConsequence: "ماذا يحدث إذا تعطلت؟",
    simpleRisk: "مستوى الخطورة",
    simpleRecommendation: "ماذا يقترح ZERO X-RAY؟",
    technicalDetails: "التفاصيل الفنية",
    riskLow: "منخفض",
    riskMedium: "متوسط",
    riskHigh: "مرتفع",
    predictionPatternProblem: "تم رصد نمط متكرر في بيانات هذه الخدمة.",
    predictionPatternConsequence: "إذا استمر هذا النمط فقد يظل مؤثرًا على أداء الخدمة أو تجربة المتعامل.",
    predictionRecommendation: "راجع الأدلة المتكررة وعالج السبب المتكرر قبل أن يتحول إلى مشكلة مستمرة.",
    simulationFailureProblem: "هذا السيناريو يوضح مشكلة محتملة قد تحدث أثناء تنفيذ الخدمة.",
    simulationNoOutcomeImpact: "المشكلة تؤثر على العمل الداخلي، لكن النتيجة الحالية لا تشير إلى فقدان المتعامل للنتيجة النهائية للخدمة.",
    simulationOutcomeImpact: "قد يؤدي هذا السيناريو إلى منع إكمال الخدمة أو تأخيرها.",
    challengeRecommendations: {
      SINGLE_POINT_OF_FAILURE: "قلّل اعتماد الخطوات التالية على هذه الخطوة حتى لا يؤدي تعطل واحد إلى توقف الخدمة.",
      CASCADING_FAILURE_PATH: "اعزل أثر التعطل حتى لا ينتقل إلى الخطوات التالية في الخدمة.",
      SLA_FRAGILITY: "أضف حدًا واضحًا لزمن الخدمة وإنذارًا مبكرًا قبل انتشار التأخير.",
      DEMAND_FRAGILITY: "أضف سعة احتياطية أو مسارًا بديلًا حتى لا يؤدي ارتفاع الطلب إلى تعطيل الخدمة.",
      CRITICAL_PATH_EXPOSURE: "قلّل الاعتماد الحرج على هذه الخطوة وأضف مسارًا بديلًا أكثر مرونة عندما يكون ذلك ممكنًا.",
      CUSTOMER_FACING_EXPOSURE: "احمِ نتيجة المتعامل بمسار بديل أو آلية استعادة عند التعطل.",
    },
    evolveProblem: "يوجد ضعف هيكلي في تصميم الخدمة تم اكتشافه أثناء اختبارات الضغط.",
    evolveConsequence: "من دون تعديل هيكلي قد يستمر نفس التعطل أو التأخير في التأثير على تقديم الخدمة.",
    preventProblem: "حدد ZERO X-RAY شرط إنذار مبكر لهذا الخطر.",
    preventConsequence: "عند وصول القيمة المراقبة إلى الحد المحدد يلزم التدخل قبل أن تتأثر الخدمة.",
    preventRecommendation: "نفّذ الإجراء الوقائي المقترح فور وصول الخطر إلى مستوى التحذير.",
    monitoringProblem: "هناك خطر في الخدمة وصل إلى مستوى يحتاج إلى متابعة.",
    monitoringBreached: "الخطر تجاوز المستوى المقبول ويحتاج إلى تدخل.",
    monitoringSafe: "الخطر ما زال داخل المستوى المقبول حاليًا.",
    monitoringRecommendation: "ابدأ بالخطر الأعلى ثم نفّذ الإجراء الوقائي المرتبط به.",
    currentValueLabel: "القيمة الحالية",
    monitoringSummaryTitle: "ملخص المراقبة",
    monitoringSummaryProblem: (count) => `يوجد ${count} مخاطر في الخدمة تحتاج إلى متابعة حاليًا.`,
    monitoringSummaryConsequence: (high, medium, low) => `${high} مرتفعة، ${medium} متوسطة، و${low} منخفضة الأولوية.`,
    monitoringSummaryRecommendation: "ابدأ بالخطر الأعلى، ثم راجع بقية المخاطر حسب الأولوية.",
    showAllMonitoring: "عرض جميع تفاصيل المراقبة",
    showCurrentAlerts: "عرض تفاصيل التنبيهات الحالية",
    showHistoricalAlerts: (count) => `سجل التنبيهات السابقة (${count})`,
    affectedSummary: (affected, total) => `قد تتأثر ${affected} من أصل ${total} خطوات في الخدمة.`,
    foundAcrossTargets: (count) => `تم اكتشاف نفس المشكلة في ${count} ${count === 1 ? "خطوة" : "خطوات"} من الخدمة.`,
    highestRiskLabel: "أعلى خطورة",
    groupedDetails: (count) => `عرض الخطوات المتأثرة (${count})`,
    preventionAcrossTargets: (count) => `يوجد ${count} ${count === 1 ? "نقطة إنذار" : "نقاط إنذار"} مرتبطة بنفس الخطر.`,
  },

};

const SCENARIO_VARIABLE_FIELDS = {
  VOLUME_SURGE: [
    { name: "demand_multiplier", label: "Demand multiplier", type: "number", step: "0.1", default: 2 },
    { name: "time_horizon_days", label: "Time horizon (days)", type: "number", step: "1", default: 30 },
  ],
  INTEGRATION_FAILURE: [
    { name: "failed_integration_id", label: "Failed integration", type: "integration-select" },
    { name: "failure_duration_hours", label: "Failure duration (hours)", type: "number", step: "1", default: 24 },
  ],
  SLA_BREACH: [
    { name: "breached_step_id", label: "Breached step", type: "step-select" },
    { name: "delay_multiplier", label: "Delay multiplier", type: "number", step: "0.1", default: 3 },
  ],
  CASCADING_STEP_FAILURE: [
    { name: "origin_step_id", label: "Origin step", type: "step-select" },
    { name: "failure_probability", label: "Failure probability (0-1)", type: "number", step: "0.05", default: 0.8 },
  ],
};

const CHALLENGE_STRATEGY_OPTIONS = [
  "EXHAUSTIVE_STEP_FAILURE",
  "EXHAUSTIVE_INTEGRATION_FAILURE",
  "SLA_STRESS",
  "DEMAND_STRESS",
];

function GroundingBadge({ type }) {
  const cls =
    type === "FACT" ? "sd-status sd-status-good" :
    type === "PREDICTION" ? "sd-status sd-status-info" :
    "sd-status sd-status-warning";
  return <span className={cls}>{type}</span>;
}

function MethodologyNote({ marker }) {
  if (!marker || !marker.note) return null;
  return (
    <p className="sd-empty" style={{ marginTop: 10 }}>
      ⚙ {marker.note}
    </p>
  );
}

function EvidenceList({ evidence }) {
  if (!evidence || evidence.length === 0) return null;
  return (
    <ul className="sd-intel-evidence">
      {evidence.map((entry, index) => (
        <li key={index}>
          <GroundingBadge type={entry.type} />
          <span>{entry.detail}</span>
        </li>
      ))}
    </ul>
  );
}

function AlertCard({ alert, copy }) {
  return (
    <article className="sd-intel-item">
      <div className="sd-section-heading">
        <div>
          <strong>{copy.monitoringProblem}</strong>
          <small>
            {alert.created_at}
            {alert.is_historical && ` · ${copy.historicalAlertBadge}`}
          </small>
        </div>
        <span className={alert.status === "TRIGGERED" ? "sd-status sd-status-bad" : "sd-status sd-status-good"}>
          {alert.status === "TRIGGERED" ? copy.alertStatusTriggered : copy.alertStatusResolved}
        </span>
      </div>
      <p className="sd-empty">
        <b>{copy.currentValueLabel}:</b> {alert.current_value ?? copy.noDataYet} ·{" "}
        <b>{copy.thresholdLabel}:</b> {alert.threshold_value}
      </p>
      <Disclosure label={copy.technicalDetails}>
        <p><code>{alert.trigger_id}</code></p>
        {alert.evidence && <p>{alert.evidence}</p>}
      </Disclosure>
    </article>
  );
}

// =====================================================================
// GOVERNMENT DECISION-MAKER LANGUAGE (audit fix -- Intelligence Panel
// presentation only): translates already-computed technical codes
// (vulnerability_type, evolution_type, prediction_type, trigger_type,
// scenario_type) into plain-language headlines, and structures each
// insight's ALREADY-EXISTING fields (severity_basis, explanation,
// evidence, current_state/proposed_state, exposure_before/after,
// etc.) into a consistent What happened -> Why it matters -> Impact
// -> Recommendation -> Before/After narrative. This is a pure display
// transformation: every number, score, and piece of text still comes
// straight from the same API fields as before -- nothing is invented,
// no Ollama call is added, no backend/agent code is touched. A field
// that has no data for a given insight (e.g. Simulate has no
// before/after) simply isn't rendered for that row, rather than
// showing a placeholder.
const VULNERABILITY_LABELS = {
  en: {
    SINGLE_POINT_OF_FAILURE: "One step can stop the service",
    CASCADING_FAILURE_PATH: "A failure can spread to later steps",
    SLA_FRAGILITY: "A delay can push the service beyond its expected time",
    DEMAND_FRAGILITY: "High demand can slow or interrupt the service",
    CRITICAL_PATH_EXPOSURE: "The service depends heavily on this step",
    CUSTOMER_FACING_EXPOSURE: "This issue can directly affect the customer",
  },
  ar: {
    SINGLE_POINT_OF_FAILURE: "تعطل خطوة واحدة قد يوقف الخدمة",
    CASCADING_FAILURE_PATH: "تعطل خطوة قد يمتد إلى الخطوات التالية",
    SLA_FRAGILITY: "التأخير قد يتجاوز الوقت المتوقع للخدمة",
    DEMAND_FRAGILITY: "ارتفاع الطلب قد يبطئ الخدمة أو يعطلها",
    CRITICAL_PATH_EXPOSURE: "الخدمة تعتمد بشكل كبير على هذه الخطوة",
    CUSTOMER_FACING_EXPOSURE: "هذه المشكلة قد تؤثر على المتعامل مباشرة",
  },
};

const EVOLUTION_LABELS = {
  en: {
    ADD_REDUNDANCY: "Add a backup path",
    DECOUPLE_DEPENDENCY: "Remove a rigid dependency",
    ADD_SLA_SAFEGUARD: "Add a service-time safeguard",
    ADD_CAPACITY_BUFFER: "Add a capacity buffer",
    ADD_CITIZEN_SAFEGUARD: "Add a citizen safeguard",
  },
  ar: {
    ADD_REDUNDANCY: "إضافة مسار احتياطي",
    DECOUPLE_DEPENDENCY: "إزالة اعتمادية غير مرنة",
    ADD_SLA_SAFEGUARD: "إضافة ضمانة لزمن الخدمة",
    ADD_CAPACITY_BUFFER: "إضافة هامش طاقة",
    ADD_CITIZEN_SAFEGUARD: "إضافة ضمانة لصالح المتعامل",
  },
};

const PREDICTION_TYPE_LABELS = {
  en: { EVIDENCE_BASED: "Based on repeated evidence", MODEL_INFERRED: "Inferred pattern" },
  ar: { EVIDENCE_BASED: "مبني على أدلة متكررة", MODEL_INFERRED: "نمط مستنتج" },
};

const TRIGGER_TYPE_LABELS = {
  en: {
    CHALLENGE_RECURRENCE_TRIGGER: "Recurrence watch",
    PREDICTION_EARLY_WARNING_TRIGGER: "Early-warning watch",
  },
  ar: {
    CHALLENGE_RECURRENCE_TRIGGER: "مراقبة التكرار",
    PREDICTION_EARLY_WARNING_TRIGGER: "مراقبة الإنذار المبكر",
  },
};

const SCENARIO_TYPE_LABELS = {
  en: {
    VOLUME_SURGE: "Demand spike",
    INTEGRATION_FAILURE: "Integration failure",
    SLA_BREACH: "Service-time breach",
    CASCADING_STEP_FAILURE: "Step failure",
  },
  ar: {
    VOLUME_SURGE: "ارتفاع الطلب",
    INTEGRATION_FAILURE: "فشل تكامل",
    SLA_BREACH: "خرق زمن الخدمة",
    CASCADING_STEP_FAILURE: "فشل خطوة",
  },
};

const CHALLENGE_STRATEGY_LABELS = {
  en: {
    EXHAUSTIVE_STEP_FAILURE: "Step failure stress test",
    EXHAUSTIVE_INTEGRATION_FAILURE: "Integration failure stress test",
    SLA_STRESS: "Service-time stress test",
    DEMAND_STRESS: "Demand stress test",
  },
  ar: {
    EXHAUSTIVE_STEP_FAILURE: "اختبار تعطل الخطوات",
    EXHAUSTIVE_INTEGRATION_FAILURE: "اختبار تعطل التكاملات",
    SLA_STRESS: "اختبار ضغط زمن الخدمة",
    DEMAND_STRESS: "اختبار ضغط ارتفاع الطلب",
  },
};

const WATCH_METRIC_LABELS = {
  en: {
    challenge_severity: "Risk severity",
    prediction_confidence: "Prediction confidence",
  },
  ar: {
    challenge_severity: "درجة خطورة المشكلة",
    prediction_confidence: "درجة ثقة التنبؤ",
  },
};

const SCENARIO_FIELD_LABELS = {
  en: {
    demand_multiplier: "Demand multiplier",
    time_horizon_days: "Time horizon (days)",
    failed_integration_id: "Failed integration",
    failure_duration_hours: "Failure duration (hours)",
    breached_step_id: "Affected step",
    delay_multiplier: "Delay multiplier",
    origin_step_id: "Origin step",
    failure_probability: "Failure probability",
  },
  ar: {
    demand_multiplier: "مضاعف حجم الطلب",
    time_horizon_days: "الفترة الزمنية (بالأيام)",
    failed_integration_id: "التكامل المتعطل",
    failure_duration_hours: "مدة التعطل (بالساعات)",
    breached_step_id: "الخطوة المتأثرة",
    delay_multiplier: "مضاعف التأخير",
    origin_step_id: "الخطوة التي يبدأ منها التعطل",
    failure_probability: "احتمالية التعطل",
  },
};

const RISK_LEVEL_LABELS = {
  en: { LOW: "Low", MEDIUM: "Medium", HIGH: "High" },
  ar: { LOW: "منخفض", MEDIUM: "متوسط", HIGH: "مرتفع" },
};

function riskBucketCode(value) {
  const score = Number(value);
  if (!Number.isFinite(score)) return null;
  if (score >= 20) return "HIGH";
  if (score >= 10) return "MEDIUM";
  return "LOW";
}

function riskLabel(lang, value) {
  const code = riskBucketCode(value);
  if (!code) return null;
  return RISK_LEVEL_LABELS[lang]?.[code] || RISK_LEVEL_LABELS.en[code];
}

function Disclosure({ label, children }) {
  return (
    <details className="sd-disclosure">
      <summary>{label}</summary>
      <div className="sd-disclosure-content">{children}</div>
    </details>
  );
}

function SimpleInsight({ problem, consequence, risk, riskMax = 100, riskBucketValue, recommendation, copy }) {
  const bucketValue = riskBucketValue ?? risk;
  return (
    <div>
      {problem && <p><b>{copy.simpleProblem}</b><br />{problem}</p>}
      {consequence && <p><b>{copy.simpleConsequence}</b><br />{consequence}</p>}
      {risk !== undefined && risk !== null && (
        <p>
          <b>{copy.simpleRisk}</b><br />
          {riskLabel(copy === COPY.ar ? "ar" : "en", bucketValue)} — {risk}/{riskMax}
        </p>
      )}
      {recommendation && <p><b>{copy.simpleRecommendation}</b><br />{recommendation}</p>}
    </div>
  );
}

function translateCode(dictionary, lang, code) {
  // Never invents a label for an unknown code -- falls back to the
  // raw code exactly as before, so nothing can ever go blank/wrong.
  return (dictionary[lang] && dictionary[lang][code]) || code;
}

function statusPillClass(status) {
  if (status === "success") return "sd-status sd-status-good";
  if (status === "error") return "sd-status sd-status-bad";
  if (status === "loading") return "sd-status sd-status-info";
  return "sd-status";
}

function Stepper({ stages }) {
  return (
    <div className="sd-intel-stepper">
      {stages.map((stage, index) => (
        <div key={stage.key} className="sd-intel-stepper-node">
          <span className={`sd-intel-stepper-dot sd-intel-stepper-dot-${stage.status}`}>
            {stage.status === "success" ? "✓" : stage.status === "error" ? "!" : index + 1}
          </span>
          <span className="sd-intel-stepper-label">{stage.label}</span>
          {index < stages.length - 1 && <span className="sd-intel-stepper-connector" />}
        </div>
      ))}
    </div>
  );
}

function StageCard({ title, hint, status, error, children, action, copy }) {
  const statusLabel =
    status === "success" ? copy.statusDone :
    status === "error" ? copy.statusError :
    status === "loading" ? copy.statusRunning :
    copy.statusIdle;

  return (
    <section className="sd-card sd-intel-stage">
      <div className="sd-section-heading">
        <div>
          <strong>{title}</strong>
          {hint && <small>{hint}</small>}
        </div>
        <div className="sd-intel-stage-actions">
          <span className={statusPillClass(status)}>
            {status === "loading" && <span className="sd-live-dot" />}
            {statusLabel}
          </span>
          {action}
        </div>
      </div>

      {status === "error" && error && (
        <p className="sd-action-error">
          {error} <small>{copy.retryHint}</small>
        </p>
      )}

      {children}
    </section>
  );
}

function useStage() {
  const [state, setState] = useState({ status: "idle", data: null, error: "" });

  async function run(apiCall) {
    setState((prev) => ({ ...prev, status: "loading", error: "" }));
    try {
      const data = await apiCall();
      setState({ status: "success", data, error: "" });
      return data;
    } catch (err) {
      setState({ status: "error", data: null, error: err?.message || "Request failed." });
      return null;
    }
  }

  function reset() {
    setState({ status: "idle", data: null, error: "" });
  }

  return [state, run, reset];
}

export default function IntelligencePanel({ serviceId, futureSteps = [], integrations = [] }) {
  const { hasPermission } = useAuth();
  const { lang } = useLanguage();
  const copy = COPY[lang] || COPY.en;

  const [predict, runPredict, resetPredict] = useStage();
  const [simulate, runSimulate, resetSimulate] = useStage();
  const [challenge, runChallenge, resetChallenge] = useStage();
  const [evolve, runEvolve, resetEvolve] = useStage();
  const [prevent, runPrevent, resetPrevent] = useStage();
  const [monitoring, runMonitoring, resetMonitoring] = useStage();
  const [alerts, runAlerts] = useStage();
  const [schedule, setSchedule] = useState({ enabled: false, frequency: "daily" });
  const [scheduleStatus, setScheduleStatus] = useState({ loading: false, message: "", error: "" });

  const [simulateMode, setSimulateMode] = useState("auto"); // "auto" | "prediction" | "manual"
  const [manualScenarioType, setManualScenarioType] = useState("VOLUME_SURGE");
  const [manualVariables, setManualVariables] = useState({});

  const [linkPredictionToChallenge, setLinkPredictionToChallenge] = useState(true);
  const [selectedStrategies, setSelectedStrategies] = useState([]);

  useEffect(() => {
    let active = true;
    if (!serviceId || !hasPermission("future:monitor")) return () => { active = false; };
    getMonitoringSchedule(serviceId)
      .then((data) => {
        if (active && data?.schedule) {
          setSchedule({ enabled: Boolean(data.schedule.enabled), frequency: data.schedule.frequency || "daily" });
        }
      })
      .catch(() => {});
    return () => { active = false; };
  }, [serviceId, hasPermission]);

  if (!serviceId) {
    return (
      <div className="sd-panel">
        <section className="sd-card">
          <p className="sd-empty">{copy.noServiceId}</p>
        </section>
      </div>
    );
  }

  const stepOptions = futureSteps.map((step, index) => {
    const id = `STEP-${step.step_number ?? index + 1}`;
    return { id, label: `${id} — ${step.name || "Untitled step"}` };
  });
  const integrationOptions = integrations
    .filter((name) => String(name || "").trim())
    .map((name, index) => {
      const id = `INTEGRATION-${String(index + 1).padStart(3, "0")}`;
      return { id, label: `${id} — ${name}` };
    });

  // Presentation-only lookup: Future Engine returns targets such as STEP-2.
  // Resolve them back to the actual step produced by the journey redesign so
  // the executive view shows the real journey step name/description instead
  // of a technical ID. No engine data or calculations are changed here.
  const futureStepById = new Map(
    futureSteps.map((step, index) => [
      `STEP-${step.step_number ?? index + 1}`,
      { ...step, __displayNumber: step.step_number ?? index + 1 },
    ])
  );

  function targetFromValue(value) {
    const match = String(value || "").match(/STEP-\d+/i);
    return match ? match[0].toUpperCase() : null;
  }

  function resolveJourneyStep(value) {
    const target = targetFromValue(value);
    return target ? futureStepById.get(target) || null : null;
  }

  function journeyStepTitle(value) {
    const target = targetFromValue(value);
    const step = resolveJourneyStep(value);
    if (!step) return target || String(value || "—");
    const prefix = lang === "ar" ? `الخطوة ${step.__displayNumber}` : `Step ${step.__displayNumber}`;
    return `${prefix} — ${step.name || step.action || target}`;
  }

  function journeyStepDescription(value) {
    const step = resolveJourneyStep(value);
    if (!step) return "";
    const candidates = [
      step.detailed_description,
      step.action,
      step.reason,
      step.assistant_action,
      step.customer_role,
    ];
    const name = String(step.name || "").trim().toLowerCase();
    return String(candidates.find((item) => {
      const text = String(item || "").trim();
      return text && text.toLowerCase() !== name;
    }) || "").trim();
  }

  function uniqueJourneyTargets(items, getter) {
    const seen = new Set();
    const result = [];
    items.forEach((item) => {
      const raw = getter(item);
      const target = targetFromValue(raw);
      if (target && !seen.has(target)) {
        seen.add(target);
        result.push(target);
      }
    });
    return result;
  }

  const predictionId = predict.data?.prediction_id || null;
  const challengeId = challenge.data?.challenge_id || null;
  const evolutionId = evolve.data?.evolution_id || null;

  function handleManualVariableChange(name, value) {
    setManualVariables((prev) => ({ ...prev, [name]: value }));
  }

  function fieldsForScenarioType(type) {
    return SCENARIO_VARIABLE_FIELDS[type] || [];
  }

  async function handleRunPredict() {
    const data = await runPredict(() => predictService(serviceId, lang));
    if (data) {
      // A fresh prediction makes any downstream link (Simulate's
      // "from prediction" mode, Challenge's linked prediction_id)
      // stale -- reset so the chain of real IDs stays honest.
      resetSimulate();
      resetChallenge();
      resetEvolve();
      resetPrevent();
    }
  }

  async function handleRunSimulate() {
    // Defense in depth against duplicate/overlapping requests -- the
    // button below is already disabled while loading, this guard
    // covers the handler itself being invoked again some other way.
    if (simulate.status === "loading") return;

    if (simulateMode === "auto") {
      await runSimulate(() =>
        createScenario(serviceId, {
          trigger_type: "AUTO",
          lang,
        })
      );
      return;
    }
    if (simulateMode === "prediction") {
      await runSimulate(() =>
        createScenario(serviceId, {
          trigger_type: "PREDICTION",
          prediction_id: predictionId,
          lang,
        })
      );
      return;
    }
    const fields = fieldsForScenarioType(manualScenarioType);
    const variables = {};
    for (const field of fields) {
      const raw = manualVariables[field.name];
      const value = raw === undefined || raw === "" ? field.default : raw;
      variables[field.name] = field.type === "number" ? Number(value) : value;
    }
    await runSimulate(() =>
      createScenario(serviceId, {
        trigger_type: "MANUAL",
        scenario_type: manualScenarioType,
        variables,
        lang,
      })
    );
  }

  async function handleRunChallenge() {
    const payload = { lang };
    if (selectedStrategies.length > 0) payload.strategies = selectedStrategies;
    if (linkPredictionToChallenge && predictionId) payload.prediction_id = predictionId;
    const data = await runChallenge(() => createChallenge(serviceId, payload));
    if (data) {
      resetEvolve();
      resetPrevent();
    }
  }

  async function handleRunEvolve() {
    const data = await runEvolve(() => createEvolution(serviceId, challengeId, lang));
    if (data) resetPrevent();
  }

  async function handleRunPrevent() {
    const data = await runPrevent(() => createPrevention(serviceId, evolutionId, lang));
    if (data) resetMonitoring();
  }

  async function handleRunMonitoring() {
    const preventionId = prevent.data?.prevention_id;
    const data = await runMonitoring(() => runMonitoringCheck(serviceId, preventionId, lang));
    if (data) {
      // Refresh the stored alert list right after a check so newly
      // created/resolved alerts are visible immediately -- still a
      // real read of real stored data, not a guess at what changed.
      runAlerts(() => listAlerts(serviceId));
    }
  }

  async function handleSaveMonitoringSchedule() {
    setScheduleStatus({ loading: true, message: "", error: "" });
    try {
      const data = await updateMonitoringSchedule(serviceId, schedule.enabled, schedule.frequency);
      if (data?.schedule) {
        setSchedule({ enabled: Boolean(data.schedule.enabled), frequency: data.schedule.frequency || "daily" });
      }
      setScheduleStatus({ loading: false, message: copy.scheduleSaved, error: "" });
    } catch (err) {
      setScheduleStatus({ loading: false, message: "", error: translateApiError(err?.message, lang) || "Request failed." });
    }
  }

  function toggleStrategy(strategy) {
    setSelectedStrategies((prev) =>
      prev.includes(strategy) ? prev.filter((item) => item !== strategy) : [...prev, strategy]
    );
  }

  return (
    <div className="sd-panel sd-intel-panel">
      <section className="sd-card">
        <div className="sd-section-heading">
          <div>
            <span className="sd-kicker">{copy.kicker}</span>
            <h3>{copy.title}</h3>
            <small>{copy.intro}</small>
          </div>
        </div>

      </section>

      <Stepper
        stages={[
          { key: "predict", label: copy.stepperPredict, status: predict.status },
          { key: "simulate", label: copy.stepperSimulate, status: simulate.status },
          { key: "challenge", label: copy.stepperChallenge, status: challenge.status },
          { key: "evolve", label: copy.stepperEvolve, status: evolve.status },
          { key: "prevent", label: copy.stepperPrevent, status: prevent.status },
        ]}
      />

      {/* ---------------- PREDICT ---------------- */}
      <StageCard
        title={copy.predictTitle}
        hint={copy.predictHint}
        status={predict.status}
        error={translateApiError(predict.error, lang)}
        copy={copy}
        action={hasPermission("future:predict") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={predict.status === "loading"}
            onClick={handleRunPredict}
          >
            {predict.status === "success" ? copy.rerunPredict : copy.runPredict}
          </button>
        ) : null}
      >
        {predict.data && (
          <>
            {predict.data.predictions?.length === 0 && (
              <p className="sd-empty">{copy.noPredictions}</p>
            )}

            {predict.data.predictions?.map((item) => (
              <article key={item.prediction_id} className="sd-intel-item">
                <SimpleInsight
                  problem={copy.predictionPatternProblem}
                  consequence={copy.predictionPatternConsequence}
                  risk={item.confidence}
                  riskMax={1}
                  riskBucketValue={item.confidence != null ? Number(item.confidence) * 100 : null}
                  recommendation={copy.predictionRecommendation}
                  copy={copy}
                />
                <Disclosure label={copy.technicalDetails}>
                  <p className="sd-empty">
                    {copy.predictionIdLabel}: <code>{item.prediction_id}</code> · {item.category} · {item.prediction_type}
                  </p>
                  <p>{item.statement}</p>
                  {item.confidence_basis && <p className="sd-empty">{item.confidence_basis}</p>}
                  {item.explanation && <p>{item.explanation}</p>}
                  <EvidenceList evidence={item.signals?.map((sig) => ({ type: "FACT", detail: `${sig.source}: ${sig.detail}` }))} />
                </Disclosure>
              </article>
            ))}

            <Disclosure label={copy.technicalDetails}>
              <p className="sd-empty">
                {copy.dataSufficiency}: <b>{predict.data.data_sufficiency?.verdict}</b> (
                {predict.data.data_sufficiency?.analyses_count} {copy.analysesLabel},{" "}
                {predict.data.data_sufficiency?.journeys_count} {copy.journeysLabel}) ·{" "}
                {copy.predictionIdLabel}: <code>{predictionId}</code>
              </p>
              <MethodologyNote marker={predict.data.score_methodology} />
            </Disclosure>
          </>
        )}
      </StageCard>

      {/* ---------------- SIMULATE ---------------- */}
      <StageCard
        title={copy.simulateTitle}
        hint={copy.simulateHint}
        status={simulate.status}
        error={translateApiError(simulate.error, lang)}
        copy={copy}
        action={hasPermission("future:simulate") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={
              simulate.status === "loading" ||
              (simulateMode === "prediction" && !predictionId)
            }
            onClick={handleRunSimulate}
          >
            {simulate.status === "success" ? copy.rerunSimulate : copy.runSimulate}
          </button>
        ) : null}
      >
        <div className="sd-intel-mode-toggle">
          <label>
            <input
              type="radio"
              checked={simulateMode === "auto"}
              onChange={() => setSimulateMode("auto")}
            />
            {copy.autoScenario}
          </label>
          <label>
            <input
              type="radio"
              checked={simulateMode === "prediction"}
              onChange={() => setSimulateMode("prediction")}
            />
            {copy.fromPrediction}{!predictionId && ` ${copy.runPredictFirst}`}
          </label>
          <label>
            <input
              type="radio"
              checked={simulateMode === "manual"}
              onChange={() => setSimulateMode("manual")}
            />
            {copy.manualScenario}
          </label>
        </div>

        {simulateMode === "auto" && (
          <p className="sd-empty">{copy.autoScenarioHint}</p>
        )}

        {simulateMode === "manual" && (
          <div className="sd-intel-form">
            <label>
              {copy.scenarioTypeLabel}
              <select
                value={manualScenarioType}
                onChange={(e) => {
                  setManualScenarioType(e.target.value);
                  setManualVariables({});
                }}
              >
                {Object.keys(SCENARIO_VARIABLE_FIELDS).map((type) => (
                  <option key={type} value={type}>{translateCode(SCENARIO_TYPE_LABELS, lang, type)}</option>
                ))}
              </select>
            </label>

            {fieldsForScenarioType(manualScenarioType).map((field) => (
              <label key={field.name}>
                {translateCode(SCENARIO_FIELD_LABELS, lang, field.name)}
                {field.type === "step-select" ? (
                  stepOptions.length > 0 ? (
                    <select
                      value={manualVariables[field.name] || ""}
                      onChange={(e) => handleManualVariableChange(field.name, e.target.value)}
                    >
                      <option value="">{copy.selectStep}</option>
                      {stepOptions.map((opt) => (
                        <option key={opt.id} value={opt.id}>{opt.label}</option>
                      ))}
                    </select>
                  ) : (
                    <span className="sd-empty">{copy.noStepsAvailable}</span>
                  )
                ) : field.type === "integration-select" ? (
                  integrationOptions.length > 0 ? (
                    <select
                      value={manualVariables[field.name] || ""}
                      onChange={(e) => handleManualVariableChange(field.name, e.target.value)}
                    >
                      <option value="">{copy.selectIntegration}</option>
                      {integrationOptions.map((opt) => (
                        <option key={opt.id} value={opt.id}>{opt.label}</option>
                      ))}
                    </select>
                  ) : (
                    <span className="sd-empty">{copy.noIntegrationsAvailable}</span>
                  )
                ) : (
                  <input
                    type="number"
                    step={field.step}
                    placeholder={String(field.default)}
                    value={manualVariables[field.name] ?? ""}
                    onChange={(e) => handleManualVariableChange(field.name, e.target.value)}
                  />
                )}
              </label>
            ))}
          </div>
        )}

        {simulate.data && !simulate.data.auto_scenarios && (() => {
          const affected = simulate.data.affected_steps?.length || 0;
          const total = futureSteps.length || affected;
          const consequence = affected > 0
            ? `${copy.affectedSummary(affected, total)} ${simulate.data.citizen_outcome_affected ? copy.simulationOutcomeImpact : copy.simulationNoOutcomeImpact}`
            : (simulate.data.citizen_outcome_affected ? copy.simulationOutcomeImpact : copy.simulationNoOutcomeImpact);
          return (
            <article className="sd-intel-item">
              <SimpleInsight
                problem={`${translateCode(SCENARIO_TYPE_LABELS, lang, simulate.data.scenario?.scenario_type)} — ${copy.simulationFailureProblem}`}
                consequence={consequence}
                risk={simulate.data.overall_risk_score}
                copy={copy}
              />
              <Disclosure label={copy.technicalDetails}>
                <p>{copy.scenarioIdLabel}: <code>{simulate.data.scenario_id}</code> · {simulate.data.scenario?.scenario_type} ({simulate.data.scenario?.trigger_type})</p>
                <p>{copy.citizenImpact}: {simulate.data.citizen_impact?.score} — {simulate.data.citizen_impact?.basis}</p>
                <p>{copy.governmentImpact}: {simulate.data.government_impact?.score} — {simulate.data.government_impact?.basis}</p>
                <p>{copy.likelihoodLabel}: {simulate.data.likelihood} ({simulate.data.likelihood_source})</p>
                {simulate.data.outcome_impact_reason && <p>{simulate.data.outcome_impact_reason}</p>}
                {simulate.data.affected_steps?.length > 0 && <p>{simulate.data.affected_steps.map((st) => `${st.name} [${st.status}]`).join(", ")}</p>}
                {simulate.data.possible_outcomes?.[0]?.description && <p>{simulate.data.possible_outcomes[0].description}</p>}
                <EvidenceList evidence={simulate.data.assumptions?.map((a) => ({ type: "ASSUMPTION", detail: `${a.variable_name}: ${a.reason}` }))} />
                <MethodologyNote marker={simulate.data.score_methodology} />
              </Disclosure>
            </article>
          );
        })()}

        {simulate.data && simulate.data.auto_scenarios && (
          simulate.data.auto_scenarios.length === 0 ? (
            <p className="sd-empty">{copy.noAutoScenarios}</p>
          ) : (
            <>
              <p className="sd-empty">{copy.autoScenariosHeading}</p>
              {simulate.data.auto_scenarios.map((item) => {
                const affected = item.affected_steps?.length || 0;
                const total = futureSteps.length || affected;
                const consequence = affected > 0
                  ? `${copy.affectedSummary(affected, total)} ${item.citizen_outcome_affected ? copy.simulationOutcomeImpact : copy.simulationNoOutcomeImpact}`
                  : (item.citizen_outcome_affected ? copy.simulationOutcomeImpact : copy.simulationNoOutcomeImpact);
                return (
                  <article key={item.scenario_id} className="sd-intel-item">
                    <SimpleInsight
                      problem={`${copy.autoCategories[item.scenario?.auto_category] || translateCode(SCENARIO_TYPE_LABELS, lang, item.scenario?.scenario_type)} — ${copy.simulationFailureProblem}`}
                      consequence={consequence}
                      risk={item.overall_risk_score}
                      copy={copy}
                    />
                    <Disclosure label={copy.technicalDetails}>
                      <p>{copy.scenarioIdLabel}: <code>{item.scenario_id}</code> · {item.scenario?.scenario_type}</p>
                      <p>{copy.citizenImpact}: {item.citizen_impact?.score} — {item.citizen_impact?.basis}</p>
                      <p>{copy.governmentImpact}: {item.government_impact?.score} — {item.government_impact?.basis}</p>
                      <p>{copy.likelihoodLabel}: {item.likelihood} ({item.likelihood_source})</p>
                      {item.outcome_impact_reason && <p>{item.outcome_impact_reason}</p>}
                      {item.affected_steps?.length > 0 && <p>{item.affected_steps.map((st) => `${st.name} [${st.status}]`).join(", ")}</p>}
                      {item.possible_outcomes?.[0]?.description && <p>{item.possible_outcomes[0].description}</p>}
                      <EvidenceList evidence={item.assumptions?.map((a) => ({ type: "ASSUMPTION", detail: `${a.variable_name}: ${a.reason}` }))} />
                    </Disclosure>
                  </article>
                );
              })}
              <Disclosure label={copy.technicalDetails}><MethodologyNote marker={simulate.data.score_methodology} /></Disclosure>
            </>
          )
        )}
      </StageCard>

      {/* ---------------- CHALLENGE ---------------- */}
      <StageCard
        title={copy.challengeTitle}
        hint={copy.challengeHint}
        status={challenge.status}
        error={translateApiError(challenge.error, lang)}
        copy={copy}
        action={hasPermission("future:challenge") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={challenge.status === "loading"}
            onClick={handleRunChallenge}
          >
            {challenge.status === "success" ? copy.rerunChallenge : copy.runChallenge}
          </button>
        ) : null}
      >
        <div className="sd-intel-form">
          <label>
            <input
              type="checkbox"
              checked={linkPredictionToChallenge}
              disabled={!predictionId}
              onChange={(e) => setLinkPredictionToChallenge(e.target.checked)}
            />
            {copy.linkPrediction} {predictionId ? `(${predictionId})` : copy.noneYet}
          </label>
          <div className="sd-intel-mode-toggle">
            {CHALLENGE_STRATEGY_OPTIONS.map((strategy) => (
              <label key={strategy}>
                <input
                  type="checkbox"
                  checked={selectedStrategies.includes(strategy)}
                  onChange={() => toggleStrategy(strategy)}
                />
                {translateCode(CHALLENGE_STRATEGY_LABELS, lang, strategy)}
              </label>
            ))}
          </div>
          <small className="sd-empty">{copy.strategiesHint}</small>
        </div>

        {challenge.data && (() => {
          const vulnerabilities = challenge.data.vulnerabilities || [];
          const groups = Object.values(vulnerabilities.reduce((acc, item) => {
            const key = item.vulnerability_type || "OTHER";
            (acc[key] ||= []).push(item);
            return acc;
          }, {}));
          return (
            <>
              {vulnerabilities.length === 0 && <p className="sd-empty">{copy.noVulnerabilities}</p>}
              {groups.map((items) => {
                const first = items[0];
                const highest = Math.max(...items.map((x) => Number(x.severity ?? 0)));
                const affectsOutcome = items.some((x) => x.citizen_outcome_affected);
                const journeyTargets = uniqueJourneyTargets(items, (item) => item.target);
                const affectedCount = journeyTargets.length || items.length;
                return (
                  <article key={first.vulnerability_type} className="sd-intel-item">
                    <SimpleInsight
                      problem={translateCode(VULNERABILITY_LABELS, lang, first.vulnerability_type)}
                      consequence={`${copy.foundAcrossTargets(affectedCount)} ${affectsOutcome ? copy.simulationOutcomeImpact : copy.simulationNoOutcomeImpact}`}
                      risk={highest}
                      recommendation={copy.challengeRecommendations?.[first.vulnerability_type]}
                      copy={copy}
                    />
                    <Disclosure label={copy.groupedDetails(affectedCount)}>
                      {items.map((item) => {
                        const description = journeyStepDescription(item.target);
                        return (
                          <div key={item.vulnerability_id} className="sd-empty" style={{ marginBottom: 10 }}>
                            <b>{journeyStepTitle(item.target)}</b> · <b>{copy.severityLabel}:</b> {item.severity}/100
                            {description && <div>{description}</div>}
                          </div>
                        );
                      })}
                    </Disclosure>
                    <Disclosure label={copy.technicalDetails}>
                      {items.map((item) => (
                        <div key={item.vulnerability_id}>
                          <p>{copy.challengeIdLabel}: <code>{challengeId}</code> · {item.vulnerability_type} · {copy.targetLabel}: {item.target}</p>
                          {item.severity_basis && <p>{item.severity_basis}</p>}
                          {item.outcome_impact_reason && <p>{item.outcome_impact_reason}</p>}
                          {item.explanation && <p>{item.explanation}</p>}
                          <EvidenceList evidence={item.evidence} />
                        </div>
                      ))}
                    </Disclosure>
                  </article>
                );
              })}
              <Disclosure label={copy.technicalDetails}>
                <p>{copy.challengeIdLabel}: <code>{challengeId}</code> · {challenge.data.cases_executed?.length} {copy.casesExecuted}</p>
                <MethodologyNote marker={challenge.data.score_methodology} />
              </Disclosure>
            </>
          );
        })()}
      </StageCard>

      {/* ---------------- EVOLVE ---------------- */}
      <StageCard
        title={copy.evolveTitle}
        hint={copy.evolveHint}
        status={evolve.status}
        error={translateApiError(evolve.error, lang)}
        copy={copy}
        action={hasPermission("future:evolve") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={evolve.status === "loading" || !challengeId}
            onClick={handleRunEvolve}
          >
            {evolve.status === "success" ? copy.rerunEvolve : copy.runEvolve}
          </button>
        ) : null}
      >
        {!challengeId && <p className="sd-empty">{copy.needChallengeFirst}</p>}

        {evolve.data && (() => {
          const proposals = evolve.data.proposals || [];
          const groups = Object.values(proposals.reduce((acc, item) => {
            const key = item.evolution_type || "OTHER";
            (acc[key] ||= []).push(item);
            return acc;
          }, {}));
          return (
            <>
              {proposals.length === 0 && <p className="sd-empty">{copy.noProposals}</p>}
              {groups.map((items) => {
                const first = items[0];
                const highest = Math.max(...items.map((x) => Number(x.exposure_before ?? 0)));
                const journeyTargets = uniqueJourneyTargets(items, (item) => item.target || item.fixes_vulnerability_id);
                const affectedCount = journeyTargets.length || items.length;
                const itemsByTarget = items.reduce((acc, item) => {
                  const target = targetFromValue(item.target || item.fixes_vulnerability_id) || item.target || item.proposal_id;
                  (acc[target] ||= []).push(item);
                  return acc;
                }, {});
                return (
                  <article key={first.evolution_type} className="sd-intel-item">
                    <SimpleInsight
                      problem={`${translateCode(EVOLUTION_LABELS, lang, first.evolution_type)} — ${copy.evolveProblem}`}
                      consequence={`${copy.foundAcrossTargets(affectedCount)} ${copy.evolveConsequence}`}
                      risk={highest}
                      recommendation={translateCode(EVOLUTION_LABELS, lang, first.evolution_type)}
                      copy={copy}
                    />
                    <Disclosure label={copy.groupedDetails(affectedCount)}>
                      {Object.entries(itemsByTarget).map(([target, targetItems]) => {
                        const description = journeyStepDescription(target);
                        const changes = [...new Set(targetItems.map((item) => `${item.exposure_before ?? "—"} → ${item.exposure_after_estimate ?? copy.notCalculable}`))];
                        return (
                          <div key={target} className="sd-empty" style={{ marginBottom: 10 }}>
                            <b>{journeyStepTitle(target)}</b>
                            {description && <div>{description}</div>}
                            <div><b>{copy.insightBeforeAfter}:</b> {changes.join(" · ")}</div>
                          </div>
                        );
                      })}
                    </Disclosure>
                    <Disclosure label={copy.technicalDetails}>
                      {items.map((item) => (
                        <div key={item.proposal_id}>
                          <p>{copy.evolutionIdLabel}: <code>{item.proposal_id}</code> · {item.evolution_type} · {copy.fixesLabel}: {item.fixes_vulnerability_id}</p>
                          {item.current_state && <p>{item.current_state}</p>}
                          {item.proposed_state && <p>{item.proposed_state}</p>}
                          {item.exposure_calculation_basis && <p>{item.exposure_calculation_basis}</p>}
                          {item.explanation && <p>{item.explanation}</p>}
                          <EvidenceList evidence={item.grounding} />
                        </div>
                      ))}
                    </Disclosure>
                  </article>
                );
              })}
              {evolve.data.skipped_vulnerabilities?.length > 0 && (
                <Disclosure label={copy.technicalDetails}><p>{copy.skippedLabel}: {evolve.data.skipped_vulnerabilities.map((x) => x.reason).join("; ")}</p></Disclosure>
              )}
              <Disclosure label={copy.technicalDetails}>
                <p>{copy.evolutionIdLabel}: <code>{evolutionId}</code> · {copy.basedOnChallenge} <code>{evolve.data.challenge_id}</code></p>
                <MethodologyNote marker={evolve.data.score_methodology} />
              </Disclosure>
            </>
          );
        })()}
      </StageCard>

      {/* ---------------- PREVENT ---------------- */}
      <StageCard
        title={copy.preventTitle}
        hint={copy.preventHint}
        status={prevent.status}
        error={translateApiError(prevent.error, lang)}
        copy={copy}
        action={hasPermission("future:prevent") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={prevent.status === "loading" || !evolutionId}
            onClick={handleRunPrevent}
          >
            {prevent.status === "success" ? copy.rerunPrevent : copy.runPrevent}
          </button>
        ) : null}
      >
        {!evolutionId && <p className="sd-empty">{copy.needEvolveFirst}</p>}

        {prevent.data && (() => {
          const triggers = prevent.data.triggers || [];
          const groups = Object.values(triggers.reduce((acc, item) => {
            const key = item.watch_metric || "OTHER";
            (acc[key] ||= []).push(item);
            return acc;
          }, {}));
          return (
            <>
              {triggers.length === 0 && <p className="sd-empty">{copy.noTriggers}</p>}
              {groups.map((items) => {
                const first = items[0];
                const highest = Math.max(...items.map((x) => Number(x.threshold_value ?? 0)));
                const itemsByTarget = items.reduce((acc, item) => {
                  const target = targetFromValue(item.source_vulnerability_id || item.watch_scope || item.source_proposal_id);
                  const key = target || "SERVICE";
                  (acc[key] ||= []).push(item);
                  return acc;
                }, {});
                const journeyTargets = Object.keys(itemsByTarget).filter((target) => target !== "SERVICE");
                const affectedCount = journeyTargets.length || Object.keys(itemsByTarget).length;
                return (
                  <article key={first.watch_metric} className="sd-intel-item">
                    <SimpleInsight
                      problem={`${copy.preventProblem} ${translateCode(WATCH_METRIC_LABELS, lang, first.watch_metric)}`}
                      consequence={`${copy.preventionAcrossTargets(affectedCount)} ${copy.preventConsequence}`}
                      risk={highest}
                      recommendation={copy.preventRecommendation}
                      copy={copy}
                    />
                    <Disclosure label={copy.groupedDetails(affectedCount)}>
                      {Object.entries(itemsByTarget).map(([target, targetItems]) => {
                        const description = target === "SERVICE" ? "" : journeyStepDescription(target);
                        const thresholds = [...new Set(targetItems.map((item) => item.threshold_value))];
                        return (
                          <div key={target} className="sd-empty" style={{ marginBottom: 10 }}>
                            <b>{target === "SERVICE" ? (lang === "ar" ? "الخدمة بالكامل" : "Whole service") : journeyStepTitle(target)}</b>
                            {description && <div>{description}</div>}
                            <div><b>{copy.watchingLabel}:</b> {translateCode(WATCH_METRIC_LABELS, lang, first.watch_metric)} · <b>{copy.thresholdLabel}:</b> {thresholds.join("، ")}</div>
                          </div>
                        );
                      })}
                    </Disclosure>
                    <Disclosure label={copy.technicalDetails}>
                      {items.map((item) => (
                        <div key={item.trigger_id}>
                          <p>{copy.preventionIdLabel}: <code>{item.trigger_id}</code> · {item.trigger_type}</p>
                          <p>{copy.watchingLabel}: {item.watch_metric} · {item.watch_scope}</p>
                          <p>{copy.thresholdLabel}: {item.threshold_value} — {item.threshold_basis}</p>
                          {item.explanation && <p>{item.explanation}</p>}
                          {item.action_if_triggered && <p>{item.action_if_triggered}</p>}
                          <EvidenceList evidence={item.grounding} />
                        </div>
                      ))}
                    </Disclosure>
                  </article>
                );
              })}
              {prevent.data.skipped_proposals?.length > 0 && (
                <Disclosure label={copy.technicalDetails}><p>{copy.skippedLabel}: {prevent.data.skipped_proposals.map((x) => x.reason).join("; ")}</p></Disclosure>
              )}
              <Disclosure label={copy.technicalDetails}>
                <p>{copy.preventionIdLabel}: <code>{prevent.data.prevention_id}</code> · {copy.basedOnEvolution} <code>{prevent.data.evolution_id}</code></p>
                <MethodologyNote marker={prevent.data.score_methodology} />
              </Disclosure>
            </>
          );
        })()}
      </StageCard>

      {/* ---------------- MONITORING & ALERTS ---------------- */}
      <StageCard
        title={copy.monitoringTitle}
        hint={copy.monitoringHint}
        status={monitoring.status}
        error={translateApiError(monitoring.error, lang)}
        copy={copy}
        action={hasPermission("future:monitor") ? (
          <button
            className="sd-button sd-button-primary"
            type="button"
            disabled={monitoring.status === "loading" || !prevent.data?.prevention_id}
            onClick={handleRunMonitoring}
          >
            {monitoring.status === "success" ? copy.rerunMonitoring : copy.runMonitoring}
          </button>
        ) : null}
      >
        {!prevent.data?.prevention_id && <p className="sd-empty">{copy.needPreventFirst}</p>}

        <p className="sd-empty">ℹ {copy.monitoringNote}</p>

        {hasPermission("future:monitor") && (
          <div className="sd-intel-form">
            <strong>{copy.scheduledMonitoring}</strong>
            <small className="sd-empty">{copy.scheduledMonitoringHint}</small>
            <label>
              <input
                type="checkbox"
                checked={schedule.enabled}
                onChange={(e) => setSchedule((prev) => ({ ...prev, enabled: e.target.checked }))}
              />
              {copy.enabledLabel}
            </label>
            <label>
              {copy.frequencyLabel}
              <select
                value={schedule.frequency}
                disabled={!schedule.enabled}
                onChange={(e) => setSchedule((prev) => ({ ...prev, frequency: e.target.value }))}
              >
                <option value="hourly">{copy.hourlyLabel}</option>
                <option value="daily">{copy.dailyLabel}</option>
              </select>
            </label>
            <button
              className="sd-button"
              type="button"
              disabled={scheduleStatus.loading}
              onClick={handleSaveMonitoringSchedule}
            >
              {copy.saveSchedule}
            </button>
            <small className="sd-empty">{copy.notificationsDatabaseOnly}</small>
            {scheduleStatus.message && <small className="sd-empty">{scheduleStatus.message}</small>}
            {scheduleStatus.error && <p className="sd-action-error">{scheduleStatus.error}</p>}
          </div>
        )}

        {monitoring.data && (() => {
          const checks = monitoring.data.checks || [];
          const active = checks.filter((check) => check.breached);
          const scored = active.map((check) => ({
            ...check,
            displayRisk: Number(check.current_value ?? check.threshold_value ?? 0),
          }));
          const high = scored.filter((check) => riskBucketCode(check.displayRisk) === "HIGH").length;
          const medium = scored.filter((check) => riskBucketCode(check.displayRisk) === "MEDIUM").length;
          const low = scored.filter((check) => riskBucketCode(check.displayRisk) === "LOW").length;
          const highest = scored.reduce((best, check) => !best || check.displayRisk > best.displayRisk ? check : best, null);

          return (
            <>
              {active.length > 0 ? (
                <article className="sd-intel-item">
                  <SimpleInsight
                    problem={copy.monitoringSummaryProblem(active.length)}
                    consequence={copy.monitoringSummaryConsequence(high, medium, low)}
                    risk={highest?.displayRisk}
                    recommendation={copy.monitoringSummaryRecommendation}
                    copy={copy}
                  />
                </article>
              ) : (
                <p className="sd-empty">{copy.monitoringSafe}</p>
              )}

              {checks.length > 0 && (
                <Disclosure label={copy.showAllMonitoring}>
                  {checks.map((check) => (
                    <div key={check.trigger_id} className="sd-empty">
                      <b>{translateCode(WATCH_METRIC_LABELS, lang, check.watch_metric)}:</b> {check.current_value ?? copy.noDataYet} / {copy.thresholdLabel} {check.threshold_value} · <b>{check.breached ? copy.breachedYes : copy.breachedNo}</b>
                      <Disclosure label={copy.technicalDetails}>
                        <p>{check.trigger_id} · {check.watch_metric}</p>
                        {check.checked_against && <p>{copy.checkedAgainst}: {check.checked_against}</p>}
                        {check.evidence && <p>{check.evidence}</p>}
                        <p>{check.alert_action}</p>
                      </Disclosure>
                    </div>
                  ))}
                </Disclosure>
              )}
              <Disclosure label={copy.technicalDetails}><MethodologyNote marker={monitoring.data.score_methodology} /></Disclosure>
            </>
          );
        })()}

        <div className="sd-section-heading" style={{ marginTop: 16 }}>
          <div>
            <strong>{copy.alertsListTitle}</strong>
          </div>
          <button
            className="sd-button sd-button-secondary"
            type="button"
            disabled={alerts.status === "loading"}
            onClick={() => runAlerts(() => listAlerts(serviceId))}
          >
            {copy.refreshAlerts}
          </button>
        </div>

        {alerts.error && <p className="sd-action-error">{translateApiError(alerts.error, lang)}</p>}

        {alerts.data && (
          alerts.data.alerts?.length === 0 ? (
            <p className="sd-empty">{copy.noAlertsYet}</p>
          ) : (
            <>
              {alerts.data.alerts.some((alert) => alert.is_current) && (() => {
                const currentAlerts = alerts.data.alerts.filter((alert) => alert.is_current);
                return (
                  <Disclosure label={`${copy.currentAlertsHeading} (${currentAlerts.length})`}>
                    {currentAlerts.map((alert) => (
                      <AlertCard key={alert.id} alert={alert} copy={copy} />
                    ))}
                  </Disclosure>
                );
              })()}

              {alerts.data.alerts.some((alert) => alert.is_historical) && (() => {
                const historicalAlerts = alerts.data.alerts.filter((alert) => alert.is_historical);
                return (
                  <Disclosure label={copy.showHistoricalAlerts(historicalAlerts.length)}>
                    {historicalAlerts.map((alert) => (
                      <AlertCard key={alert.id} alert={alert} copy={copy} />
                    ))}
                  </Disclosure>
                );
              })()}
            </>
          )
        )}
      </StageCard>
    </div>
  );
}
